# Generated by Django 5.1.6 on 2025-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='events-asset'),
        ),
    ]
